# API KEYS; Defined in secrets.py
YOUTUBE_DATA_API='placeholder'

# YOUTUBE SETTINGS 
LIKE_PLAYLIST_ID='LLjYn4RyjCCMJX67Rck4sq5A'
SPEC_CHANNEL_PLAYLIST_ID='PLa0DseGKotuAHBwFnxFEsU5qGL9F3fxe4'
SPEC_VIDEO_PLAYLIST_ID='PLa0DseGKotuA_ciqFFvpYr7hBsv3z8LLl'
ROOT_CHANNEL_ID='UCjYn4RyjCCMJX67Rck4sq5A'


# DATABASE SETTINGS
SQLALCHEMY_DATABASE_URI='sqlite:////tmp/qmp_api.db'

# CELERY SETTINGS
CELERY_BROKER_URL='pyamqp://guest@localhost//'
CELERY_RESULT_BACKEND=''
